remote_theme: mmistakes/minimal-mistakes@4.21.0
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

title: Marissa Grunes
email:
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: gone_incognita
github_username: seastar88
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

author:
  name   : "Incognita: A Portrait of Antarctica"
  avatar : "/assets/img/marissa.jpg"
  bio    : "My current book project is a work of narrative nonfiction about the Antarctic. Incognita: A Portrait of Antarctica tells the story of this awesome and fragile region through natural and human history, accounts of current scientific research, and artistic responses to the seventh continent."
  links:
    - label: ""
      icon: "fas fa-fw fa-envelope"
      url: "mailto:gone.incognita@gmail.com"
    - label: ""
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Gone_Incognita"
    

footer:
  links:
    - label: ""
      icon: "fas fa-fw fa-envelope"
      url: "mailto:gone.incognita@gmail.com"
    - label: ""
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Gone_Incognita"
    

defaults:
  # _posts
  - scope:
      path: ""
      type: 
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
